front-end/front-end.md

Esse PR adiciona um conteúdo bem legal sobre as propriedades de posicionamento do CSS

chore: add content about CSS positioning

---

Tecnologias/PHP/php.md

Meus primeiros dois centavos sobre PHP =)

Primeiras dicas de php

---

Tecnologias/Javascript/javascript.md
Áreas/Front-end/front-end.md

Apesar desse conteúdo caber em ambos os arquivos, acredito que já que a ideia é ter uma pasta para as tecnologias/linguagens esse conteúdo fica melhor dentro de Javascript

Separando javascript do front-end

---

Áreas/Front-end/front-end.md

Havia esquecido de por o link do curso.
Sorry :D

Corrigindo link HTML

---

Tecnologias/Javascript/javascript.md

Infelizmente está em Inglês, mas eu achei o material tão bom que acredito que é um link que mereça estar na lista

Dica de curso de NodeJS

---

Tecnologias/vue/vue.md

Criado repositório para o framework  vuejs e adicionado dois curso: um introdutório e outro intermediário.

adicionando repositório para o framework vuejs

---

Áreas/Front-end/front-end.md

Esse artigo é super útil para quem está começando ou mesmo que ainda está decidindo se quer seguir o caminho do frontend.

Inclusão de artigo de frontend

---

Tecnologias/Javascript/javascript.md

Eu acho a didática deles muito boa e os cursos são gratuitos, basta fazer login com o github para ter acesso.

Adicionando cursos gratuitos da Rocketseat

---

Soft Skills/soft-skills.md
Tecnologias/C/C.md
Tecnologias/Go/Go.md
Tecnologias/Node/Node.md
Tecnologias/Python/python.md
Tecnologias/Typescript/Typescript.md

Adicionei algumas novas pastas na seção Tecnologias com algumas indicações pessoais de cursos =)
Quaisquer alterações necessárias/pasta errada me informe por favor!

Adiciona cursos C, Go, Node, Python e TS

---

Tecnologias/Typescript/Typescript.md

Adicionando Mini curso gratuito de TypeScript

Mini curso de TypeScript

---

Tecnologias/Ruby/ruby.md

Neste commit, adiciono conteúdos sobre Ruby e Rails ao repositório.

Adicionando Ruby e Rails

---

Tecnologias/Rust/rust.md

Acrescentei alguns materiais sobre Rust, tanto gerais quanto específicos.

Acrescenta alguns materiais sobre Rust.

---

Tecnologias/Python/flask.md
Áreas/Front-end/front-end.md

Adicionei conteúdo no tópico Python-Flask

Adicionei conteúdo sobre Flask

---

Áreas/Front-end/front-end.md

Tópicos em que foram adicionados conteúdos: Git e Github, HTML, HTML, CSS

add conteúdos sobre frontend em tópicos existendes

---

Áreas/Ciência de Dados/ciencia_de_dados.md

Esse repositório contém conteúdos escritos por mim e em portugês baseado em um curso que estou realizando: Data Science for everyone da plataforma Datacamp. Espero poder contribuir com as anotações.

Repositório com anotações sobre Python e Ciência de dados

---

Tecnologias/Python/python.md

- [Curso completo de lógica de programação|](https://buildlab.com.br/aprenda-a-programar/), por BuildLab (Dica de [Fernando Silva](https://twitter.com/fernandomigas)): 
- [Análise de dados em Python - Câmara dos Deputados - Labhacker](https://www.youtube.com/playlist?list=PLqiFjCF_dtcymXtdjwAP4s7tRoW4CYwnH), por (LABHacker) (Dica de [Fernando Silva](https://twitter.com/fernandomigas)):

Adicionando curso de Data Science e Logica Prog

---

Soft Skills/soft-skills.md

Separa em categorias e adiciona descrição. Adiciona live sobre o que são soft skills e série de feedback.

Atualiza página de soft skills

---

Áreas/Ciência de Dados/ciencia_de_dados.md

Acrescenta indicações de livros de R

Update ciencia_de_dados.md com R

---

Tecnologias/PHP/php.md

Adding new free courses to the list

---

Tecnologias/Python/django.md

Adiciona tutoriais de django e também tutoriais de ferramentas interessantes, como datatables e rest framework, além de um curto guia de estilo. Tudo em português.

Adicionando Django (Python)

---

Soft Skills/soft-skills.md

Add artigo "O que é um Feedback Efetivo e o que ele pode fazer pela sua carreira" por Laura Lemos

Soft Skills - Feedback

---

Áreas/Front-end/front-end.md

Adicionado curso de TypeScript

Curso de TypeScript

---

Tecnologias/vue/vue.md

Adiçao do tutorial de VueJs pelo Coursetro.com

Adiçao do tutorial de VueJs pelo Coursetro.com

---

Tecnologias/C/C.md
Tecnologias/Elixir/elixir.md
Tecnologias/Ruby/ruby.md

add learn x em y minutos para C, Elixir e Ruby.

add learn x em y minutos em algumas linguagens

---

Áreas/Front-end/front-end.md

Link para curso do Marco Bruno sobre HTML e CSS.

add "Curso HTML e CSS feliz" on "HTML, CSS"

---

Tecnologias/Node/Node.md

Add link curso NodeJS com Typescript

Add Curso NodeJS com Typescript

---

Tecnologias/Go/Go.md

Add curso Golang

---

Kubernetes.md

Add link para video Kubernetes

Add video kubernetes

---

Tecnologias/React/react.md

Add link react curso

---

Soft Skills/soft-skills.md
Tecnologias/Kotlin/kotlin.md
Áreas/Back-end/back-end.md
Áreas/Front-end/front-end.md
Áreas/Marketing/marketing.md

Adicionando os conteúdos:
- [Aprendendo com o método 3C](https://www.twitch.tv/videos/1438780505?collection=6rWTuUld4BY8Sw) por [Lissa](https://twitter.com/lisstransborda)
- [Criando variáveis no Kotlin](https://dev.to/kotlinautas/criando-variaveis-no-kotlin-explorando-a-documentacao-4a4g) por [Morganna Giovanelli](https://twitter.com/morgannadev)
- [Explorando a documentação: Números em Kotlin](https://dev.to/kotlinautas/explorando-a-documentacao-numeros-em-kotlin-15go)
- [Expressões Regulares](https://dev.to/feministech/expressoes-regulares-i-o-basico-3a3j) por [Patrícia Villela](https://twitter.com/patriciaverso)
- [[pt-BR] REDAMEs DO GITHUB: IDEIAS... E DICAS](https://dev.to/acaverna/pt-br-redames-do-github-ideias-e-dicas-4p3d) por [Leticia Pegoraro](https://github.com/LelePG)
- [Como …

adicionando novos conteúdos

---

Tecnologias/Git e GitHub/git_e_github.md
Tecnologias/Go/Go.md
Tecnologias/Javascript/javascript.md

Adicionando conteúdo de JavaScript, GO e Git e Github

---

Áreas/NLP/nlp.md

Seleta de materiais sobre NLP e Linguística computacional.
Espero que seja de interesse :)

NLP e Linguística computacional

---

Tecnologias/Kotlin/kotlin.md

Adicionei uma lista de cursos reunidos pela comunidade de Kotlin (Kotlinautas) e dois artigos, um para iniciantes com Kotlin e Spring e outro para iniciantes com Kotlin e Ktor.

adicionar conteúdos de kotlin para iniciantes

---

Tecnologias/Flutter/flutter.md

Adicionei conteúdos para iniciar bem no Flutter.

Adicionando conteúdos de Flutter.

---

Tecnologias/Java/java.md

Adicionei mais um curso para iniciantes em Java e um curso de padrões de projeto com Java

Adicionando mais alguns cursos de java

---

Tecnologias/Java/java.md
Tecnologias/Java/spring.md

Adicionando alguns conteudos de spring

Adicionando Conteudo de Spring

---

Tecnologias/Java/java.md
Áreas/Banco de dados/banco_de_dados.md

Adicionando alguns conteudo sobre Banco de dados

Adicionando conteudo sobre Banco de dados

---

Tecnologias/Go/Go.md
Tecnologias/vue/vue.md
Áreas/Ciência da Computação/ciencia_da_computacao.md

- Adiciona curso de Vue 3 completo, de iniciante a avançado
- Adiciona curso de Web com Go
- Adiciona área de Ciência da Computação com um curso autodidata completo

Adiciona curso de Vue, Go e área de Ciência da Computação

---

Tecnologias/Python/python.md

Adicionei conteúdo de biopython em português e o cookbook oficial em inglês(muito utilizado em Bioinformática)

Bioinformática e Biopython adicionado

---

Tecnologias/Apex/apex.md

Curso Apex

---

Tecnologias/Swift/swift.md

Adicionando nova sessão sobre Swift.

Adicionando Swift na aba de Tecnologias

---

Tecnologias/Java/spring.md

O arquivo de Spring estava com a formatação fora do padrão dos outros arquivos.

docs: Conserta formatação do arquivo de Spring

---

Áreas/Banco de dados/banco_de_dados.md

Adicionei um novo curso, adicionei o titulo "Cursos" e modifiquei a estrutura do texto.

docs: adiciona novo curso e formata texto

---

Tecnologias/Javascript/javascript.md

Esse curso é super completo e com direito a certificação. Já tem opção de português brasileiro.
Recomendo muito.

feat: adiciona o curso do FreeCodeCamp

---

Tecnologias/Solidity/solidity.md

Adicionando conteúdos gratuitos, brasileiros e em inglês sobre a linguagem blockchain Solidity.
Referência à Issue #121

Adicionando a linguagem Solidity às tecnologias

---

Tecnologias/Elixir/elixir.md

Adicionando o Elixirschool que é um site que tem um material incrível criado pela comunidade para ensinar Elixir.

Atualizando o elixir.md

---

Áreas/DevOps/devops.md

Adicionei dois assuntos
- Resumo e Roteiros 
- Cursos
- Cursos

Atualiza Devops

---

Tecnologias/Python/python.md

Adicionei em Palestra a playlist do evento Python Week 2022 que foi realizado pela LinuxTips

Atualiza python.md com Python Week 2022

---

Tecnologias/Git e GitHub/git_e_github.md

Coloquei a divisão como Assuntos 
e adicionei o repositorio da Leticia Coelho que tem algumas dicas sobre github

Atualiza git_e_github.md (Separa o links por assuntos)

---

Tecnologias/Elixir/elixir.md

Adicionando o primeiro item da playlist de vídeos do youtube.

adicionar a sessão de vídeos do youtube

---

Tecnologias/Javascript/javascript.md

Adicionando conteúdo sobre javascript:
- Eloquent Javascript, um conteúdo em inglês e português

Atualizando javascript.md

---

Tecnologias/Ruby/ruby.md

Adicionei um curso gratuito de ruby puro

Atualizando ruby.md

---

Tecnologias/React/react.md

Adicionei o link para entender mais sobre react hooks, e uma maneira muito visual de entender os hooks contra os métodos de classe do react.

Atualizando react.md

---

Tecnologias/NextJS/nextjs.md

Adicionando um tutorial sobre nextjs e suas ferramentas para iniciantes, que da um overview sobre as principais features do next

Atualizando nextjs.md

---

Tecnologias/Elixir/elixir.md

Adicionando uma playlist de Iniciando em Elixir - codehints.

adicionando mais uma playlist do youtube

---

Tecnologias/C++/C++.md

Apostila, vídeo aula e porque utilizar C++

Adição da pasta C++

---

Áreas/Empregos/empregos.md

Não sei se é valido, mas achei interessante adicionar uma área só para empregos, pra ajudar a galera a conhecer sobre alguns sites comuns que utilizamos no dia a dia e como são alguns processos de algumas empresas

Adicionando área para empregos
